name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: [8, 10, 12]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci
      - run: npm run lint:src
      - run: npm run build
      - run: npm run lint:test
      - run: npm run test
